### ISSUE TITLE
error Line 114 optionsString is not defined

### ISSUE THREAD

**Issue by WardsParadox** [nmcspadden/PrinterGenerator#1]
First off:
Thanks for this tool, made printers easier for me before this update. I am sure this update will rock just as much.
I am having one issue trying to get it running:
$ python print_generator.py --address '10.115.100.44' --printername 'WIAD_TechServ_01' --driver 'HP LaserJet P4010 Series.gz' --location 'Willson Suite 220, RM 222A' --displayname 'TechServ Upstairs' --desc "Adds TechServ Upstairs Printer to your machine" --version '2.0'
Traceback (most recent call last):
  File "print_generator.py", line 114, in <module>
    newPlist['installcheck_script'] = newPlist['installcheck_script'].replace("OPTIONS", optionsString)
NameError: name 'optionsString' is not defined 

Removed the entire dir, and re-ran a git clone. Same issues. Not 100% sure but as far as I can read into the script it's not seeing that optionsString as existing or being optional.

**Comment by nmcspadden** [comment]
Whoops.  Fixed with commit https://github.com/nmcspadden/PrinterGenerator/commit/92a57f98e10d138c3f1cc3a35e1af04c796df32a.

**Comment by WardsParadox** [comment]
Awesome thanks! Have a great remainder of a Monday!
