### ISSUE TITLE
Apple Fuji Xerox drivers fail printer-make-and-model Comparison

### ISSUE THREAD

**Issue by jaknz** [nmcspadden/PrinterGenerator#10]
I have loaded in Apple's FujiXerox print drivers and pushed them out via Munki. However, when I create printers using PrinterGenerator, I found that the installation check script returns a not-installed status even after successful installation.

On investigation, I found that the install check script is comparing an expected printer-make-and-model key with what it reads from the installed printer, and this is not matching exactly.

The expected key is “FX ApeosPort-V C3373 PS” which I presume is being pulled from somewhere inside the PPD. However, the key returned to the check script is actually “FX ApeosPort-V C3373 PS v3018.103 PS” which is the same as what as expected except that it has the version number injected.

To work around this, I edited the AddPrinter-Template.plist file and removed the "printer-make-and-model":"DRIVER" comparison from the comparisonDict declaration. After recreating my printer definitions, I found that the installed printers pass the install check script based on the remaining three comparisons in the comparisonDict object.

Printers were created by running against a CSV with a good number of printers. I did not test this with a one-off run, but I expect it would behave the same as the change was made in the AddPrinter Template. GitHub is saying “Something went really wrong” when I try to attach my Template file, but I will paste it below.

| Printer Name | Location | Display Name | Address | Driver | Description | Options |
| --- | --- | --- | --- | --- | --- | --- |
| ICTLabBW | ICT Lab | ICT Lab B&W | 10.30.248.145 | FX ApeosPort-V C3373 PS.gz | FX ApeosPort-V C2275 | FXColorMode=Black |
| ICTLabColour | ICT Lab | ICT Lab Colour | 10.30.248.145 | FX ApeosPort-V C3373 PS.gz | FX ApeosPort-V C2275 |  |

**Comment by nmcspadden** [comment]
#14
