### ISSUE TITLE
Fuji-Xerox options case mis-match

### ISSUE THREAD

**Issue by jaknz** [nmcspadden/PrinterGenerator#15]
I'm getting this error on a set of printers. Is it possible to change the install-check script to be case-insensitive for options?

>    Running installcheck_script for AddPrinter_FindMeBW
>    Found mismatch: FXHighCapacityFeeder is 'TRUE', should be 'True'
>    installcheck_script returned 0

**Comment by jaknz** [comment]
This isn't a major issue, as I'm able to adjust the install-check manually and carry on. But I thought it might be a worthwhile general improvement. :)

**Comment by umeditor** [comment]
Does issue #13 address this issue?

**Comment by nmcspadden** [comment]
It should. Are you still seeing the mismatch with the latest version?

On Wed, Feb 3, 2016 at 1:23 PM, Patrick McNeal notifications@github.com
wrote:

> Does issue #13 https://github.com/nmcspadden/PrinterGenerator/pull/13
> address this issue?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/nmcspadden/PrinterGenerator/issues/15#issuecomment-179476941
> .

## 

## 

Nick McSpadden
nmcspadden@gmail.com

**Comment by jaknz** [comment]
I'll do a git-pull and double check when I have a few minutes. I might have a stale version; thanks for reminding me to check!

**Comment by nmcspadden** [comment]
ping
