### ISSUE TITLE
Issue with Canon

### ISSUE THREAD

**Issue by bertrandzmirov** [nmcspadden/PrinterGenerator#16]
Hello
i have this issue with canon printer. I use the csv method. Hp or Xerox printer doesn't create the error. With files is useful for you ?
Traceback (most recent call last):
      File "/tmp/munki-yzwmz7/installcheck_script", line 41, in <module>
        optionDict[builtOption.split("=")[0]] = builtOption.split("=")[1]

**Comment by henrydobson** [comment]
+1 issue is limited to Canon make.

**Comment by nmcspadden** [comment]
Can you provide the full traceback output please?

On Tue, Mar 29, 2016 at 7:29 AM, Henry Dobson notifications@github.com
wrote:

> +1 issue is limited to Canon make.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/nmcspadden/PrinterGenerator/issues/16#issuecomment-202921271

## 

## 

Nick McSpadden
nmcspadden@gmail.com

**Comment by henrydobson** [comment]
I receive:

```
Traceback (most recent call last):
  File "./installcheck.py", line 42, in <module>
    optionDict[builtOption.split("=")[0]] = builtOption.split("=")[1]
IndexError: list index out of range
```

and did a bit of digging... the lpoptOut for this scenario looks like this:

`copies=1 device-uri=lpd://192.168.1.1 finishings=3 job-cancel-after=10800 job-hold-until=no-hold job-priority=50 job-sheets=none,none marker-change-time=0 media number-up=1 printer-commands=ReportLevels printer-info='Canon BB' printer-is-accepting-jobs=true printer-is-shared=false printer-location='AA BB' printer-make-and-model='Canon iR-ADV C5250/5255 PS' printer-state=3 printer-state-change-time=1459260377 printer-state-reasons=none printer-type=10532076 printer-uri-supported=ipp://localhost/printers/AA_BB_Canon_C5255`

URI, info, location, etc substituted but this is pretty much exactly it.

**Comment by bertrandzmirov** [comment]
exactly same model of printer. Which info can be helpfull to debug ?

**Comment by carlashley** [comment]
See pull request https://github.com/nmcspadden/PrinterGenerator/pull/22 for possible fix.
Have tested this in my environment which is also a Canon system, and it resolves the issue.

**Comment by nmcspadden** [comment]
#22
