### ISSUE TITLE
Make-model mismatch on P2015 and P4010 printers

### ISSUE THREAD

**Issue by aysiu** [nmcspadden/PrinterGenerator#18]
This may be a problem with lpoptions and not PrinterGenerator itself, but it may be worth putting in a workaround.

If you run the script on a regular HP LaserJet P4010 Series, the installcheck_script will think the printer is not installed:
`Settings mismatch: printer-make-and-model is 'HP LaserJet P4010 Series', should be 'HP LaserJet P4010_P4510 Series'`

Likewise for P2015:
`Settings mismatch: printer-make-and-model is 'HP LaserJet P2015 Series', should be 'HP LaserJet P2015'`

**Comment by nmcspadden** [comment]
#14
