### ISSUE TITLE
Shlex choking on single quotation marks in locations

### ISSUE THREAD

**Issue by aysiu** [nmcspadden/PrinterGenerator#19]
If the printer-location is **'Nick McSpadden's Office'**, it can install okay if you escape the quotation mark.

But then if you run the installcheck_script, the script will choke with `raise ValueError, "No closing quotation"`

**Comment by aysiu** [comment]
I have a way around this for the printer information (name, location, IP address, etc.), but I haven't put in a pull request, because I'm not sure what to do about the options. Basically, this is my fix for the single quotation mark problem:

`def wedged_string(front_string, back_string, larger_string):
    wedged=larger_string.partition(front_string)[2].partition(back_string)[0]
    return wedged`

`optionDict = ({ "device-uri": wedged_string('device-uri=', ' finishings', lpoptOut), "printer-info": wedged_string('printer-info=', ' printer-is-accepting-jobs', lpoptOut), "printer-location": wedged_string('printer-location=\'', '\' printer-make-and-model', lpoptOut), "printer-make-and-model": wedged_string('printer-make-and-model=\'', '\' printer-state', lpoptOut) })`

**Comment by aysiu** [comment]
@nmcspadden, is it no longer choking on single quotation marks?

**Comment by nmcspadden** [comment]
I haven't made any changes in 5 years, and I wasn't really planning on fixing it.  I'll certainly accept PRs, but since this issue hasn't had any comments since 2016, I closed it. If this is something that needs to be fixed, I'll happily review code :)

**Comment by aysiu** [comment]
Makes sense. Even when I was using a fork of this, I ended up taking out my own installcheck_scripts and making the items OnDemand.
