### ISSUE TITLE
Index out of range error on options

### ISSUE THREAD

**Issue by skoontastic** [nmcspadden/PrinterGenerator#20]
Hi,

I'm starting to experiment with this, but have run into an error. Here's the output from Terminal:

`$ ./print_generator.py --printername="hs_south_copier" --driver="TOSHIBA_ColorMFP_X7.gz" --address="serveraddress.org/hs_south_copier" --location="High School South Office" --displayname="HS South Copier @ quill" --desc="Color Toshiba Copier" --options="" --version=1.0`

`$ ./print_generator.py --printername="hs_south_copier" --driver="TOSHIBA_ColorMFP_X7.gz" --address="serveraddress.org/hs_south_copier" --location="High School South Office" --displayname="HS South Copier @ quill" --desc="Color Toshiba Copier" --options="Finisher=StapleM" --version=1.0
Traceback (most recent call last):
  File "./print_generator.py", line 127, in <module>
    optionsString = getOptionsString(args.options[0])
  File "./print_generator.py", line 13, in getOptionsString
    optionsString += "\"%s\":\"%s\"" % (str(option.split('=')[0]), str(option.split('=')[1])) + ', '
IndexError: list index out of range`

If I have anything in the `--options` parameter, I get this error.

**Comment by stefan-vogel** [comment]
Hi all
Same here with

./print_generator.py --printername="ps-km-c284" --driver="KONICAMINOLTAC284.gz" --address="ps-km-c284.powersolutions.ch" --location="Erdgeschoss Reduit" --displayname="ps-kmc-284" --desc="MFP von Power Solutions Luzern" --options="PaperSources=PC210" --version=1.2

Without options, it works. Does anybody have an idea how to solve that problem?

Best, Stefan

**Comment by predrags** [comment]
ditto

Traceback (most recent call last):
  File "./print_generator.py", line 127, in <module>
    optionsString = getOptionsString(args.options[0])
  File "./print_generator.py", line 13, in getOptionsString
    optionsString += "\"%s\":\"%s\"" % (str(option.split('=')[0]), str(option.split('=')[1])) + ', '
IndexError: list index out of range

**Comment by carlashley** [comment]
Also getting the same error, and as suggested by @stefan-vogel, dropping the options from the command creates the plist file. From there, I've edited the generated plist to add the options that I need to add for the printers I'm creating.

**Comment by carlashley** [comment]
See pull request https://github.com/nmcspadden/PrinterGenerator/pull/23 for fix.

**Comment by nmcspadden** [comment]
#23
