### ISSUE TITLE
Add --catalog option

### ISSUE THREAD

**Issue by apizz** [nmcspadden/PrinterGenerator#30]
In the now archived https://github.com/grahamgilbert/printer-pkginfo, you could specify a default catalog to import the printer to, which I liked.

It appears that this is not available via the command line or in the CSV file template, and instead defaults to "testing".

Would love to be able to specify a default catalog for importing

**Comment by kevinmcox** [comment]
If you want it to be a consistent change for every printer you create you can edit **AddPrinter-Template.plist** and specify the catalog(s) you want used.

**Comment by nmcspadden** [comment]
Agreed with @kevinmcox - the template offers a way to do this for bulk edits. For individual pkginfos, you'll need to hand-edit. 

I'd accept a PR for a command line argument for this, but I have no plans to implement it myself.

**Comment by apizz** [comment]
Fair enough.  I'll go with the PLIST template
