### ISSUE TITLE
Installcheck error no attribute

### ISSUE THREAD

**Issue by ewtillman** [nmcspadden/PrinterGenerator#34]
If the location is blank then the check script fails.
Imported in printer via csv with no location defined.
Printer installs fine, no location, check script fails with error below.

Feb 19 2019 12:13:24 -0800     Traceback (most recent call last):
Feb 19 2019 12:13:24 -0800       File "/tmp/munki-62Cn03/installcheck_script", line 49, in <module>
Feb 19 2019 12:13:24 -0800         optionDict[keyName] = None if keyName not in optionDict or optionDict[keyName].strip() == "" else optionDict[keyName]
Feb 19 2019 12:13:24 -0800     AttributeError: 'NoneType' object has no attribute 'strip'

**Comment by nmcspadden** [comment]
I have no plans to fix this. The obvious solution is not to leave location blank.

**Comment by ewtillman** [comment]
That is absolutely fine, may I then suggest you update the documentation to required field instead of optional, and that it will not default to the printer name.

  --location LOCATION   Location name for printer. Optional. Defaults to
                        printername.
