### ISSUE TITLE
lpadmin errors in Catalina

### ISSUE THREAD

**Issue by jby** [nmcspadden/PrinterGenerator#36]
Have you seen this @nmcspadden?

It's from my Sal, reporting on my Munki nopkg printer setup.
<img width="952" alt="image" src="https://user-images.githubusercontent.com/1584888/70536942-f2594080-1b5f-11ea-8d3f-87681fb24e8b.png">
It started with 10.15 (could have been 10.15.1, not entirely sure).

Don't know if you're interested, but now I've reported it anyway... :)

**Comment by nmcspadden** [comment]
This is more or less expected, as it is warning you about the future. At some point in the future, this will probably simply stop working.
