### ISSUE TITLE
Specifying generic driver

### ISSUE THREAD

**Issue by flammable** [nmcspadden/PrinterGenerator#38]
Thanks for this script - I'm in the process of migrating from Graham's project to this one, due to the whole Python 2 to 3 transition.

One of my printer configs references Apple's generic driver:

`/System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/PrintCore.framework/Versions/A/Resources/Generic.ppd`

Is there any way to specify that driver in the CSV file?

**Comment by dotknewt** [comment]
If you're reading from a .csv you should be able to replace the ppd line with the generic ppd, it should take the same option (-P /path_to/ppd.ppd).

If you're having issues I've seen the lpadmin/lpoptions command not exiting correctly with the script as they give a deprecation warning that may not be handleled expectedly. I Just commented the relevant lines to avoid errors.

**Comment by flammable** [comment]
Thanks! The documentation states:

> Driver: Name of the driver file in /Library/Printers/PPDs/Contents/Resources/.

However, `Generic.ppd`  is located in `/System/Library`. I'd assume that if I put `/System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/PrintCore.framework/Versions/A/Resources/Generic.ppd` in that csv field, the script would produce a path that looks like this:

`/Library/Printers/PPDs/Contents/Resources//System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/PrintCore.framework/Versions/A/Resources/Generic.ppd`

I'll give it a shot and report back, though. My workaround might be repackaging `Generic.ppd` so I can drop it into `/Library/Printers/PPDs/Contents/Resources/`.

**Comment by flammable** [comment]
Update: it appears the code is written specifically for handling drivers in `/Library/Printers/PPDs/Contents/Resources/`, so a driver located in `/System/Library` wouldn't work. See:

https://github.com/nmcspadden/PrinterGenerator/blob/master/print_generator.py#L85
https://github.com/nmcspadden/PrinterGenerator/blob/master/print_generator.py#L175

I ended up repackaging `Generic.ppd`. Hopefully, we can get rid of that printer at some point, and it won't be an issue.

**Comment by nmcspadden** [comment]
I won't be doing any more work on this project.
