### ISSUE TITLE
installcheck_script issues if client is in the same bonjour broadcast domain?

### ISSUE THREAD

**Issue by henningkessler** [nmcspadden/PrinterGenerator#39]
Hello,

this is probably not a real issue of PrinterGenerator then more an issue with the `lpoptions` command. When the `installcheck_script` is run on a client which is in same bonjour broadcast domain as the printer and that printer is using bonjour. The output of `lpoptions -p printername` on client is that what is announced by bonjour not want is used to configure the printer. 

If you use `lpd://10.0.0.1` to configure the printer but the printer is broadcasting its services via `Ipp://bonjourname._ipp._tcp.local./` as well, the output of `lpoptions` on the client if it is in the same subnet will be `Ipp://bonjourname._ipp._tcp.local./`. The `installcheck_script`will fail and the munki will try to install the printer again and again ;-)..

I have no cloud how to handle this but it drove me insane until I run `lpoptions -p printername` while no printer was configured...

**Comment by nmcspadden** [comment]
The installcheck script is fairly naive: the options for a given printer queue are compared to the 'expected' output, and if there's any divergence, it'll determine it needs to install. Bonjour printing may introduce some wrinkles in here where the output may not match the input, and you'd have to handcraft your pkginfo data to match that expectation.

To be very clear, I don't intend to actually "fix" it, but I do appreciate you flagging this issue in case anyone else encounters the same thing.
