### ISSUE TITLE
Issue report based on Munki Group thread - regarding versioning

### ISSUE THREAD

**Issue by joncohen** [nmcspadden/PrinterGenerator#4]
It would be nice if the script could look at all of the pieces, collectively including the version so that updates could easily be made to the printer.  This way the installer could be updated without modifying the printer name.

This may not be an issue in your environment and we've been happy with the older method that you posted.  

Just a thought.

Original thread information:

Ran into another issue.  I used the updated tool to make the new pkginfo file, which worked and put in the correct settings for the device and address.  I tried to indicate the new version at 0.3 and added it to my repo.  Here is the the pkginfo file and associated output.

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>autoremove</key>
    <false/>
    <key>catalogs</key>
    <array>
        <string>testing</string>
    </array>
    <key>description</key>
    <string></string>
    <key>display_name</key>
    <string>Maintenance WC3325</string>
- show quoted text -
        '-D', 'Maintenance WC3325',
        '-v', 'lpd://10.0.10.92',
        '-P', '/Library/Printers/PPDs/Contents/Resources/Generic_PCL_OSX.ppd',
        '-E',
        '-o', 'printer-is-shared=false',
        '-o', 'printer-error-policy=abort-job' ]

for option in printerOptions.keys():
    cmd.append("-o")
    cmd.append(str(option) + "=" +  str(printerOptions[option]))

proc = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
(lpadminOut, lpadminErr) = proc.communicate()

if lpadminErr:
    print "Error: %s" % lpadminErr
    sys.exit(1)
print "Results: %s" % lpadminOut    
sys.exit(0)</string>
    <key>unattended_install</key>
    <true/>
    <key>uninstall_method</key>
    <string>uninstall_script</string>
    <key>uninstall_script</key>
    <string>#!/bin/bash
/usr/sbin/lpadmin -x MaintenanceWorkCentre</string>
    <key>uninstallable</key>
    <true/>
    <key>version</key>
    <string>0.3</string>
</dict>
</plist> 

```

verbose output:

```
* Processing manifest item AddPrinter-MaintenanceWorkCentre for install

    Looking for detail for: AddPrinter-MaintenanceWorkCentre, version latest...

    Considering 1 items with name AddPrinter-MaintenanceWorkCentre from catalog testing

    Considering item AddPrinter-MaintenanceWorkCentre, version 0.3 with minimum os version required 10.7.0

    Our OS version is 10.10.3

    Found AddPrinter-MaintenanceWorkCentre, version 0.3 in catalog testing

    Running installcheck_script for AddPrinter-MaintenanceWorkCentre

    installcheck_script returned 1

    AddPrinter-MaintenanceWorkCentre version 0.3 (or newer) is already installed.

    Looking for updates for: AddPrinter-MaintenanceWorkCentre

    Looking for updates for: AddPrinter-MaintenanceWorkCentre-0.3

    Looking for updates for: AddPrinter-MaintenanceWorkCentre--0.3
```

MSC recognizes that it is installed (indicating version 0.3 as the current version) and allows for removal of the printer. When removing the printer, it removes without issue.  If I then re-install the printer, it installs with the updated information from version 0.3 (correct address and such).

Thoughts?
# 

May 22

Did the versioning not trigger correctly on the post-install script because the address of the printer in question was different from version 0.1 to 0.3?

=== You ===
The installcheck_script compares the options that are specified by lpoptions.  If there is no change in any of the printer options, and the printername is the same, the pkginfo won't overwrite the existing print queue, because it thinks it's installed.  The idea is that the reinstall will trigger if the queue is removed, or you have new options to specify.

The version number of the pkginfo is more for admin sanity than anything else - the version number isn't actually used to make any determination about installing.

But that raises the good idea that I should make a check on _all_ specifiable options - including the address, display name, etc.  Could you please file a GitHub issue about that?

**Comment by nmcspadden** [comment]
The only way to match a previously installed printer is by PRINTERNAME - if the print queue is named differently, there's really no way to compare.

The other problem is that the version in the pkginfo is basically irrelevant here - unless the version number is written to disk somewhere, there's no safe way to determine what the version of the pkginfo was when Munki previously installed it.  Previous incarnations of this script involved writing a version receipt to disk, but that basically re-implements packaging receipts poorly, and I don't want to do that.  

The goal of this script is to be a bit more programmatic, and thus comparisons should only be made on values that we can determine at runtime.  I'm looking into comparing other things than just options - such as location, address, and drivers - but the version number itself will continue to be meaningless in terms of Munki determining whether or not to install it if nothing else is changed.

**Comment by nmcspadden** [comment]
I think I've resolved these issues with the latest commit:
https://github.com/nmcspadden/PrinterGenerator/commit/f6a92b6bfc580dbc3549b7e0979c623aecdd1f37

The installcheck_script now checks each possible option (except printername, which is the only matching key) for comparison to determine if it needs to reinstall.

Note that the version number of the pkginfo is specifically used only for Munki to consider for install - it's not used at any part of the installation check.
