### ISSUE TITLE
Remove driver requirement and make it optional instead

### ISSUE THREAD

**Issue by lifeunexpected** [nmcspadden/PrinterGenerator#41]
Since future versions of macOS 10.16 --> will slownly make printers deprecated would it be a possibility to make the need for drivers and option instead of a requirement?

SMB and LDP etc is planning to be removed and IPP is planned to take over so maybe it should be a default for IPP instead of LDP?

**Comment by nmcspadden** [comment]
I won't be doing any more work on this project.
