### ISSUE TITLE
CSV import not instantiating comparisonDict values

### ISSUE THREAD

**Issue by ryness** [nmcspadden/PrinterGenerator#6]
When I run ./print_generator.py --csv ./Template.csv with fresh files downloaded from the git, the comparisonDict array is not filled in with the proper values. Here's what comparisonDict in the resulting pkginfo looks like:

comparisonDict = { "device-uri":"ADDRESS", "printer-info":"DISPLAY_NAME", "printer-location":"LOCATION", "printer-make-and-model":"DRIVER" }

**Comment by nmcspadden** [comment]
This should now be fixed with https://github.com/nmcspadden/PrinterGenerator/commit/2e1ebf7cfbbaab4d0e30445fd9b4e29d5c816a51.
