### ISSUE TITLE
CSV import not adding protocol for address or path for driver

### ISSUE THREAD

**Issue by ryness** [nmcspadden/PrinterGenerator#7]
The following is output from --csv, whereas using the cli method adds lpd:// for -v and the full driver path to -v:
# Install the printer

cmd = [ '/usr/sbin/lpadmin',
        '-p', 'Math',
        '-L', 'Math Room',
        '-D', 'Math Room',
        '-v', '10.111.110.78',
        '-P', 'HP1600dn.ppd.gz',
        '-E',
        '-o', 'printer-is-shared=false',
        '-o', 'printer-error-policy=abort-job' ]

**Comment by nmcspadden** [comment]
Fixed with https://github.com/nmcspadden/PrinterGenerator/commit/933c9001543be666be8642f57756950f8c653dc9.
