### ISSUE TITLE
printer-make-and-model using Driver does not match what MSU -v returns for printer-make-and-model

### ISSUE THREAD

**Issue by ryness** [nmcspadden/PrinterGenerator#8]
The pkginfo resulting from either --csv or cli import shows (for an example HP 1600 printer):

"printer-make-and-model":"HP1600dn.ppd"

but when running msu -v:

Settings mismatch: printer-make-and-model is 'HP LaserJet Professional P1600dn, 6.9', should be 'HP1600dn.ppd'

**Comment by ryness** [comment]
in the pkginfo file, changing the comparisonDict array to:

"printer-make-and-model":"HP LaserJet Professional P1600dn, 6.9"

allows MSU to operate properly and recognize that in fact the printer is installed, but isn't ideal.

**Comment by nmcspadden** [comment]
This should be fixed with https://github.com/nmcspadden/PrinterGenerator/commit/87f5511ad04db021ef3911ad618d68f481b6a171.
